language: php
php:
  - '7.0'
  - nightly

before_script:
    - flags="--prefer-dist"
    - composer install $flags

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml
after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)